image: nixpkgs/nix-flakes

stages:
  - build
  - deploy

before_script:
  - mkdir -p /etc/nix
  - echo "experimental-features = nix-command flakes ca-references" >> /etc/nix/nix.conf

build:
  stage: build
  needs: []
  script:
    - nix build .

pages:
  stage: deploy
  needs: ["build"]
  script:
    - nix build .
    - cp result/share/html public
  artifacts:
    paths:
    - public/
  only:
    - master
