image: python:3.8-buster

before_script:
  - pip install -r requirements.txt

build:
  script:
    - mkdocs build
  only:
    - branches
  except:
    - master

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public/
  only:
    - master
